galaxy_info:
  author: "Rafael Marzulo"
  description: "Role para configurar o encaminhamento de logs via rsyslog."
  company: "N/A"
  license: "MIT"

  min_ansible_version: "2.12"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

dependencies:
  - role: core/baseline
