galaxy_info:
  author: "Gemini AI for @rafael"
  description: "Role para garantir a disponibilidade de ferramentas de gerenciamento de segredos (Ansible Vault)."
  company: "N/A"
  license: "MIT"

  min_ansible_version: "2.12"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

dependencies:
  - role: core/baseline
