---
# defaults file for cloud/proxmox

proxmox_enabled: true

# --- Proxmox Connection Details (ALTAMENTE SENSÍVEL!) ---
# Estas variáveis NUNCA devem ser definidas aqui ou em controle de versão.
# Use Ansible Vault ou injete via CI/CD.
proxmox_api_host: "your-proxmox-host.example.com"
proxmox_api_user: "root@pam"
proxmox_api_password: "{{ vault_proxmox_api_password }}" # Use Vault!
proxmox_api_token_id: "{{ vault_proxmox_api_token_id }}" # Use Vault!
proxmox_api_token_secret: "{{ vault_proxmox_api_token_secret }}" # Use Vault!
proxmox_api_port: 8006
proxmox_api_verify_ssl: false # Mudar para true em produção com SSL válido

# --- VMs a serem gerenciadas ---
# Lista de dicionários, cada um representando uma VM.
# Exemplo:
# proxmox_vms:
#   - name: "my-app-vm"
#     node: "pve-node1"
#     vmid: 100
#     template: "ubuntu-cloud-template"
#     cores: 2
#     memory: 2048
#     disk_size: 30
#     network_interfaces:
#       - bridge: "vmbr0"
#         ip: "192.168.1.10/24"
#         gw: "192.168.1.1"
#     state: "started" # "present", "started", "stopped", "absent"
proxmox_vms: []
