galaxy_info:
  author: "Gemini AI for @rafael"
  description: "Role para instalar e configurar o Nginx como servidor web ou proxy reverso."
  company: "N/A"
  license: "MIT"

  min_ansible_version: "2.12"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

dependencies:
  - role: core/network
