galaxy_info:
  author: "Gemini AI for @rafael"
  description: "Role para instalar e configurar o Harbor como registro de containers privado."
  company: "N/A"
  license: "MIT"

  min_ansible_version: "2.12"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

dependencies:
  - role: platform/docker
